const roles = [
  {
    _id: "650a2b3c4d5e6f7890123451",
    name: "Super Admin",
    permissions: [
      "dashboard",
      "products",
      "product",
      "categories",
      "attributes",
      "coupons",
      "orders",
      "order",
      "our-staff",
      "settings",
      "languages",
      "currencies",
      "store",
      "customization",
      "store-settings",
      "notifications",
      "edit-profile",
      "coming-soon",
      "customers",
      "customer-order",
    ],
  },
  {
    _id: "650a2b3c4d5e6f7890123452",
    name: "Admin",
    permissions: [
      "dashboard",
      "products",
      "categories",
      "attributes",
      "coupons",
      "customers",
      "orders",
      "our-staff",
      "settings",
      "languages",
      "currencies",
      "store",
      "customization",
      "store-settings",
      "notifications",
    ],
  },
  {
    _id: "650a2b3c4d5e6f7890123453",
    name: "Seller",
    permissions: [
      "dashboard",
      "products",
      "product",
      "categories",
      "attributes",
      "coupons",
      "orders",
      "order",
      "languages",
      "currencies",
      "notifications",
      "edit-profile",
      "coming-soon",
      "customers",
      "customer-order",
    ],
  },
  {
    _id: "650a2b3c4d5e6f7890123454",
    name: "Cashier",
    permissions: [
      "dashboard",
      "orders",
      "order",
      "languages",
      "currencies",
      "notifications",
      "edit-profile",
      "coming-soon",
      "customers",
      "customer-order",
    ],
  },
];

module.exports = roles;
